-- noita.lua
-- Neovim colorscheme inspired by Noita.

vim.cmd("hi clear")
if vim.fn.exists("syntax_on") == 1 then
  vim.cmd("syntax reset")
end

vim.g.colors_name = "noita"
vim.o.background = "dark"
vim.o.termguicolors = true

local p = {
  bone             = "#c7c7c7",
  gold             = "#fff66d",
  fungus           = "#ee538c",
  mana             = "#6895f3",
  portal           = "#a75cd7",
  ambrosia         = "#d5ab34",
  sludge           = "#92b71c",
  tele             = "#85c6c6",
  lava             = "#f87d01",
  glyph            = "#ce2f26",
  cloak            = "#543f4e",
  blood            = "#dc5655",
  ice              = "#7caaca",
  water            = "#7e9792",
  tablet           = "#76c395",
  hell             = "#482424",
  temple           = "#524b34",
  vault2           = "#344a3a",
  vault1           = "#181a17",
  jungle           = "#1b2513",
  base             = "#253138",
  wasteland        = "#20222d",
  pits             = "#2d1d27",
  mines            = "#111217",
  void             = "#010101",
}

-- ── Highlight table ─────────────────────────────────────────────────────────
-- String values are treated as links in the apply loop below.
local hl = {

  -- ── Base Vim ──────────────────────────────────────────────────────────────
  Normal = { fg = p.bone, bg = p.mines },
  NormalNC = "Normal",
  NormalFloat = { fg = p.bone, bg = p.void },
  FloatBorder = { fg = p.tablet, bg = p.void },
  FloatTitle = { fg = p.tele, bg = p.void, bold = true },
  ColorColumn = { bg = p.mines },
  Conceal = { fg = p.water },
  Cursor = { fg = p.void, bg = p.bone },
  lCursor = "Cursor",
  CursorIM = "Cursor",
  TermCursor = { fg = p.void, bg = p.bone },
  TermCursorNC = { fg = p.void, bg = p.water },
  CursorLine = { bg = p.wasteland },
  CursorColumn = { bg = p.wasteland },
  CursorLineNr = { fg = p.tablet, bold = true },
  Directory = { fg = p.tablet },
  DiffAdd = { bg = p.jungle, },
  DiffChange = { bg = p.vault1 },
  DiffDelete = { bg = p.hell },
  DiffText = { bg = p.vault2 },
  EndOfBuffer = { fg = p.void },
  ErrorMsg = { fg = p.glyph, bold = true },
  VertSplit = { fg = p.temple, bg = p.void },
  WinSeparator = { fg = p.temple, bg = p.void },
  Folded = { bg = p.pits, italic = true },
  FoldColumn = { fg = p.bone, bg = p.void },
  SignColumn = { fg = p.bone, bg = p.void },
  IncSearch = { fg = p.void, bg = p.lava, bold = true },
  CurSearch = { fg = p.void, bg = p.glyph, bold = true },
  YankFlash = { bg = p.ice, fg = p.bone, bold = true },
  Substitute = { fg = p.void, bg = p.blood, bold = true },
  LineNr = { fg = p.cloak },
  LineNrAbove = { fg = p.cloak },
  LineNrBelow = { fg = p.cloak },
  MatchParen = { fg = p.ambrosia, bold = true, underline = true },
  ModeMsg = { fg = p.tele, bold = true },
  MsgArea = { fg = p.bone },
  MsgSeparator = { fg = p.cloak },
  MoreMsg = { fg = p.tablet },
  NonText = { fg = p.cloak },
  Pmenu = { fg = p.portal, bg = p.void },
  PmenuSel = { fg = p.bone, bg = p.tele },
  PmenuSbar = { bg = p.mines },
  PmenuThumb = { bg = p.cloak },
  PmenuKind = { fg = p.blood, bg = p.void },
  PmenuKindSel = { fg = p.blood, bg = p.tele },
  PmenuExtra = { fg = p.water, bg = p.void },
  PmenuExtraSel = { fg = p.water, bg = p.tele },
  PmenuMatch = { fg = p.ambrosia, bold = true },
  PmenuMatchSel = { fg = p.ambrosia, bold = true },
  Question = { fg = p.tele },
  QuickFixLine = { bg = p.wasteland },
  Search = { fg = p.void, bg = p.ambrosia, bold = true },
  SpecialKey = { fg = p.water },
  SpellBad = { undercurl = true, sp = p.glyph },
  SpellCap = { undercurl = true, sp = p.lava },
  SpellLocal = { undercurl = true, sp = p.tablet },
  SpellRare = { undercurl = true, sp = p.gold },
  StatusLine = { fg = p.bone, bg = p.mines },
  StatusLineNC = { fg = p.water, bg = p.mines },
  TabLine = { fg = p.water, bg = p.mines },
  TabLineFill = { bg = p.mines },
  TabLineSel = { fg = p.bone, bg = p.cloak },
  Title = { fg = p.tele, bold = true },
  Visual = { bg = p.base },
  VisualNOS = { bg = p.base },
  WarningMsg = { fg = p.lava, bold = true },
  Whitespace = { fg = p.cloak },
  WildMenu = { fg = p.bone, bg = p.cloak },
  WinBar = { fg = p.bone, bg = p.mines },
  WinBarNC = { fg = p.water, bg = p.mines },

  -- ── Syntax ────────────────────────────────────────────────────────────────
  Comment = { fg = p.tablet, italic = true },
  Constant = { fg = p.ambrosia },
  String = { fg = p.sludge },
  Character = { fg = p.sludge },
  Number = { fg = p.ambrosia },
  Boolean = { fg = p.ambrosia },
  Float = { fg = p.ambrosia },
  Identifier = { fg = p.portal },
  Function = { fg = p.fungus },
  Statement = { fg = p.portal },
  Conditional = { fg = p.portal },
  Repeat = { fg = p.portal },
  Label = { fg = p.portal },
  Operator = { fg = p.lava },
  Keyword = { fg = p.portal },
  Exception = { fg = p.blood },
  PreProc = { fg = p.tele },
  Include = { fg = p.tele },
  Define = { fg = p.tele },
  Macro = { fg = p.tele },
  PreCondit = { fg = p.tele },
  Type = { fg = p.mana },
  StorageClass = { fg = p.mana },
  Structure = { fg = p.mana },
  Typedef = { fg = p.mana },
  Special = { fg = p.gold },
  SpecialChar = { fg = p.sludge },
  Tag = { fg = p.tele },
  Delimiter = { fg = p.bone },
  SpecialComment = { fg = p.tablet, italic = true },
  Debug = { fg = p.lava },
  Underlined = { underline = true },
  Ignore = { fg = p.water },
  Error = { fg = p.glyph, bold = true },
  Todo = { fg = p.void, bg = p.tele, bold = true },

  -- ── Treesitter ────────────────────────────────────────────────────────────
  ["@variable"] = { fg = p.bone },
  ["@variable.builtin"] = { fg = p.ambrosia },
  ["@variable.parameter"] = { fg = p.bone },
  ["@variable.member"] = { fg = p.tele },
  ["@constant"] = { fg = p.ambrosia },
  ["@constant.builtin"] = { fg = p.gold, bold = true },
  ["@constant.macro"] = { fg = p.ambrosia },
  ["@module"] = { fg = p.ambrosia },
  ["@module.builtin"] = { fg = p.ambrosia },
  ["@label"] = { fg = p.tele },
  ["@string"] = { fg = p.sludge },
  ["@string.documentation"] = { fg = p.sludge, italic = true },
  ["@string.regexp"] = { fg = p.lava },
  ["@string.escape"] = { fg = p.blood },
  ["@string.special"] = { fg = p.ambrosia },
  ["@string.special.symbol"] = { fg = p.ambrosia },
  ["@string.special.url"] = { fg = p.mana, underline = true },
  ["@character"] = { fg = p.sludge },
  ["@character.special"] = { fg = p.ambrosia },
  ["@number"] = { fg = p.gold },
  ["@number.float"] = { fg = p.gold },
  ["@boolean"] = { fg = p.gold, bold = true },
  ["@function"] = { fg = p.fungus },
  ["@function.builtin"] = { fg = p.ambrosia, bold = true },
  ["@function.call"] = { fg = p.fungus },
  ["@function.macro"] = { fg = p.fungus },
  ["@function.method"] = { fg = p.fungus },
  ["@function.method.call"] = { fg = p.fungus },
  ["@constructor"] = { fg = p.mana },
  ["@operator"] = { fg = p.lava },
  ["@keyword"] = { fg = p.portal },
  ["@keyword.coroutine"] = { fg = p.portal },
  ["@keyword.function"] = { fg = p.portal },
  ["@keyword.operator"] = { fg = p.portal },
  ["@keyword.import"] = { fg = p.portal },
  ["@keyword.storage"] = { fg = p.mana },
  ["@keyword.repeat"] = { fg = p.portal },
  ["@keyword.return"] = { fg = p.portal },
  ["@keyword.debug"] = { fg = p.lava },
  ["@keyword.exception"] = { fg = p.blood },
  ["@keyword.conditional"] = { fg = p.portal },
  ["@keyword.conditional.ternary"] = { fg = p.portal },
  ["@keyword.directive"] = { fg = p.portal },
  ["@keyword.directive.define"] = { fg = p.portal },
  ["@punctuation.delimiter"] = { fg = p.water },
  ["@punctuation.bracket"] = { fg = p.water },
  ["@punctuation.special"] = { fg = p.gold },
  ["@comment"] = { fg = p.tablet, italic = true },
  ["@comment.documentation"] = { fg = p.tablet, italic = true },
  ["@comment.error"] = { fg = p.glyph, bold = true },
  ["@comment.warning"] = { fg = p.lava, bold = true },
  ["@comment.todo"] = { fg = p.void, bg = p.tablet, bold = true },
  ["@comment.note"] = { fg = p.void, bg = p.tablet, bold = true },
  ["@type"] = { fg = p.mana },
  ["@type.builtin"] = { fg = p.mana, bold = true },
  ["@type.definition"] = { fg = p.mana },
  ["@attribute"] = { fg = p.lava },
  ["@attribute.builtin"] = { fg = p.ambrosia },
  ["@property"] = { fg = p.tele },
  ["@tag"] = { fg = p.tele },
  ["@tag.builtin"] = { fg = p.ambrosia },
  ["@tag.attribute"] = { fg = p.portal },
  ["@tag.delimiter"] = { fg = p.water },
  ["@diff.plus"] = { bg = p.jungle },
  ["@diff.minus"] = { bg = p.hell, fg = p.lava },
  ["@diff.delta"] = { bg = p.vault1 },
  ["@markup.strong"] = { fg = p.lava, bold = true },
  ["@markup.italic"] = { fg = p.fungus, italic = true },
  ["@markup.strikethrough"] = { strikethrough = true },
  ["@markup.underline"] = { underline = true },
  ["@markup.heading"] = { fg = p.tele, bold = true },
  ["@markup.heading.1"] = { fg = p.tele, bold = true },
  ["@markup.heading.2"] = { fg = p.tablet, bold = true },
  ["@markup.heading.3"] = { fg = p.sludge, bold = true },
  ["@markup.heading.4"] = { fg = p.gold },
  ["@markup.heading.5"] = { fg = p.water },
  ["@markup.heading.6"] = { fg = p.water },
  ["@markup.quote"] = { fg = p.tablet, italic = true },
  ["@markup.math"] = { fg = p.gold },
  ["@markup.link"] = { fg = p.tele, underline = true },
  ["@markup.link.label"] = { fg = p.tele },
  ["@markup.link.url"] = { fg = p.mana, underline = true },
  ["@markup.raw"] = { fg = p.bone },
  ["@markup.raw.block"] = { fg = p.bone },
  ["@markup.list"] = { fg = p.tele },
  ["@markup.list.checked"] = { fg = p.sludge },
  ["@markup.list.unchecked"] = { fg = p.water },

  -- ── LSP semantic tokens ───────────────────────────────────────────────────
  ["@lsp.type.class"] = "@type",
  ["@lsp.type.comment"] = "@comment",
  ["@lsp.type.decorator"] = "@attribute",
  ["@lsp.type.enum"] = "@type",
  ["@lsp.type.enumMember"] = "@constant",
  ["@lsp.type.event"] = "@type",
  ["@lsp.type.function"] = "@function",
  ["@lsp.type.interface"] = "@type",
  ["@lsp.type.keyword"] = "@keyword",
  ["@lsp.type.macro"] = "@constant.macro",
  ["@lsp.type.method"] = "@function.method",
  ["@lsp.type.modifier"] = "@keyword",
  ["@lsp.type.namespace"] = "@module",
  ["@lsp.type.number"] = "@number",
  ["@lsp.type.operator"] = "@operator",
  ["@lsp.type.parameter"] = "@variable.parameter",
  ["@lsp.type.property"] = "@property",
  ["@lsp.type.regexp"] = "@string.regexp",
  ["@lsp.type.string"] = "@string",
  ["@lsp.type.struct"] = "@type",
  ["@lsp.type.type"] = "@type",
  ["@lsp.type.typeParameter"] = "@type",
  ["@lsp.type.variable"] = "@variable",
  ["@lsp.typemod.function.defaultLibrary"] = "@function.builtin",
  ["@lsp.typemod.variable.defaultLibrary"] = "@variable.builtin",
  ["@lsp.typemod.type.defaultLibrary"] = "@type.builtin",

  -- ── Diagnostics ───────────────────────────────────────────────────────────
  DiagnosticError = { fg = p.glyph },
  DiagnosticWarn = { fg = p.lava },
  DiagnosticInfo = { fg = p.tele },
  DiagnosticHint = { fg = p.tablet },
  DiagnosticOk = { fg = p.tablet },
  DiagnosticVirtualTextError = { fg = p.glyph, bg = p.hell, italic = true },
  DiagnosticVirtualTextWarn = { fg = p.lava, bg = p.wasteland, italic = true },
  DiagnosticVirtualTextInfo = { fg = p.tele, bg = p.wasteland, italic = true },
  DiagnosticVirtualTextHint = { fg = p.tablet, bg = p.jungle, italic = true },
  DiagnosticVirtualTextOk = { fg = p.tablet, bg = p.jungle, italic = true },
  DiagnosticUnderlineError = { undercurl = true, sp = p.glyph },
  DiagnosticUnderlineWarn = { undercurl = true, sp = p.lava },
  DiagnosticUnderlineInfo = { undercurl = true, sp = p.tele },
  DiagnosticUnderlineHint = { undercurl = true, sp = p.tablet },
  DiagnosticUnderlineOk = { undercurl = true, sp = p.tablet },
  DiagnosticFloatingError = { fg = p.glyph },
  DiagnosticFloatingWarn = { fg = p.lava },
  DiagnosticFloatingInfo = { fg = p.tele },
  DiagnosticFloatingHint = { fg = p.tablet },
  DiagnosticSignError = { fg = p.glyph },
  DiagnosticSignWarn = { fg = p.lava },
  DiagnosticSignInfo = { fg = p.tele },
  DiagnosticSignHint = { fg = p.tablet },

  -- ── flash.nvim ───────────────────────────────────────────────────────────────
  FlashLabel = { fg = p.void, bg = p.tele, bold = true },
  FlashMatch = { fg = p.void, bg = p.ambrosia, bold = true },
  FlashCurrent = { fg = p.void, bg = p.lava, bold = true },
  FlashBackdrop = { fg = p.water },
  FlashPrompt = { fg = p.bone, bg = p.mines },
  FlashPromptMode = { fg = p.tele, bg = p.mines, bold = true },
  FlashCursor = "Cursor",

  -- ── gitsigns ─────────────────────────────────────────────────────────────
  GitSignsAdd = { fg = p.sludge },
  GitSignsChange = { fg = p.tablet },
  GitSignsDelete = { fg = p.glyph },
  GitSignsAddNr = { fg = p.tablet },
  GitSignsChangeNr = { fg = p.tablet },
  GitSignsDeleteNr = { fg = p.glyph },
  GitSignsAddLn = { bg = p.jungle },
  GitSignsChangeLn = { bg = p.wasteland },
  GitSignsDeleteLn = { bg = p.hell },
  GitSignsAddInline = { fg = p.void, bg = p.tablet },
  GitSignsChangeInline = { fg = p.void, bg = p.lava },
  GitSignsDeleteInline = { fg = p.void, bg = p.glyph },

  -- ── snacks.nvim ───────────────────────────────────────────────────────────
  SnacksNormal = "NormalFloat",
  SnacksNormalNC = "NormalFloat",
  SnacksWinBar = { fg = p.tele, bold = true },
  SnacksWinBarNC = "SnacksWinBar",
  SnacksBackdrop = { fg = p.water, bg = p.void },
  SnacksDashboardHeader = { fg = p.sludge, bold = true },
  SnacksDashboardFooter = { fg = p.water, italic = true },
  SnacksDashboardTitle = { fg = p.tele, bold = true },
  SnacksDashboardDesc = { fg = p.bone },
  SnacksDashboardKey = { fg = p.fungus, bold = true },
  SnacksDashboardIcon = { fg = p.tablet },
  SnacksDashboardDir = { fg = p.water },
  SnacksDashboardFile = { fg = p.bone },
  SnacksDashboardSpecial = { fg = p.water },
  SnacksDashboardTerminal = { fg = p.bone },
  SnacksNotifierDebug = { fg = p.water },
  SnacksNotifierTrace = { fg = p.water },
  SnacksNotifierInfo = { fg = p.bone },
  SnacksNotifierWarn = { fg = p.lava },
  SnacksNotifierError = { fg = p.glyph },
  SnacksNotifierBorderDebug = { fg = p.temple },
  SnacksNotifierBorderTrace = { fg = p.temple },
  SnacksNotifierBorderInfo = { fg = p.tele },
  SnacksNotifierBorderWarn = { fg = p.lava },
  SnacksNotifierBorderError = { fg = p.glyph },
  SnacksNotifierTitleDebug = { fg = p.water, bold = true },
  SnacksNotifierTitleTrace = { fg = p.water, bold = true },
  SnacksNotifierTitleInfo = { fg = p.tele, bold = true },
  SnacksNotifierTitleWarn = { fg = p.lava, bold = true },
  SnacksNotifierTitleError = { fg = p.glyph, bold = true },
  SnacksNotifierIconDebug = { fg = p.water },
  SnacksNotifierIconTrace = { fg = p.water },
  SnacksNotifierIconInfo = { fg = p.tele },
  SnacksNotifierIconWarn = { fg = p.lava },
  SnacksNotifierIconError = { fg = p.glyph },
  SnacksNotifierFooterDebug = { fg = p.water },
  SnacksNotifierFooterTrace = { fg = p.water },
  SnacksNotifierFooterInfo = { fg = p.tele },
  SnacksNotifierFooterWarn = { fg = p.lava },
  SnacksNotifierFooterError = { fg = p.glyph },
  SnacksIndent = { fg = p.cloak },
  SnacksIndentScope = { fg = p.cloak },
  SnacksPicker = { fg = p.bone, bg = p.void },
  SnacksPickerBorder = { fg = p.tablet, bg = p.void },
  SnacksPickerInput = { fg = p.bone, bg = p.void },
  SnacksPickerPrompt = { fg = p.tele },
  SnacksPickerDir = { fg = p.water },
  SnacksPickerFile = { fg = p.bone },
  SnacksPickerMatch = { fg = p.ambrosia, bold = true },
  SnacksPickerSelected = { fg = p.fungus },
  SnacksPickerToggle = { fg = p.tele },
  SnacksPickerInputBorder = { fg = p.tablet },
  SnacksPickerInputTitle = { fg = p.tele, bold = true },
  SnacksPickerListTitle = { fg = p.bone, bold = true },
  SnacksPickerPreviewTitle = { fg = p.water, bold = true },
  SnacksInputBorder = { fg = p.tablet },
  SnacksInputTitle = { fg = p.tele, bold = true },

  -- ── noice.nvim ────────────────────────────────────────────────────────────
  NoiceCmdline = { fg = p.bone, bg = p.void },
  NoiceCmdlineIcon = { fg = p.tele },
  NoiceCmdlineIconSearch = { fg = p.ambrosia },
  NoiceCmdlinePopup = { fg = p.bone, bg = p.void },
  NoiceCmdlinePopupBorder = { fg = p.tablet },
  NoiceCmdlinePopupBorderSearch = { fg = p.ambrosia },
  NoiceCmdlinePopupTitle = { fg = p.tele, bold = true },
  NoicePopup = { fg = p.bone, bg = p.void },
  NoicePopupBorder = { fg = p.tablet },
  NoiceConfirm = { fg = p.bone, bg = p.void },
  NoiceConfirmBorder = { fg = p.tablet },
  NoiceMini = { fg = p.bone, bg = p.mines },
  NoiceFormatProgressDone = { fg = p.void, bg = p.tablet },
  NoiceFormatProgressTodo = { fg = p.water, bg = p.mines },
  NoiceLspProgressSpinner = { fg = p.tele },
  NoiceLspProgressTitle = { fg = p.bone },
  NoiceLspProgressClient = { fg = p.water },

  -- ── which-key ─────────────────────────────────────────────────────────────
  WhichKey = { fg = p.fungus },
  WhichKeyGroup = { fg = p.tele },
  WhichKeyDesc = { fg = p.bone },
  WhichKeySeparator = { fg = p.water },
  WhichKeyBorder = { fg = p.tablet },
  WhichKeyNormal = { bg = p.void },
  WhichKeyValue = { fg = p.water },

}

-- ── Terminal colors ──────────────────────────────────────────────────────────
vim.g.terminal_color_0  = p.void     -- black
vim.g.terminal_color_1  = p.glyph    -- red
vim.g.terminal_color_2  = p.sludge   -- green
vim.g.terminal_color_3  = p.ambrosia -- yellow
vim.g.terminal_color_4  = p.mana     -- blue
vim.g.terminal_color_5  = p.fungus   -- magenta
vim.g.terminal_color_6  = p.tele     -- cyan
vim.g.terminal_color_7  = p.bone     -- white
vim.g.terminal_color_8  = p.water    -- bright black
vim.g.terminal_color_9  = p.blood    -- bright red
vim.g.terminal_color_10 = p.tablet   -- bright green
vim.g.terminal_color_11 = p.gold     -- bright yellow
vim.g.terminal_color_12 = p.ice      -- bright blue
vim.g.terminal_color_13 = p.lava     -- bright magenta
vim.g.terminal_color_14 = p.portal   -- bright cyan
vim.g.terminal_color_15 = p.bone     -- bright white

-- ── Apply ────────────────────────────────────────────────────────────────────
for group, spec in pairs(hl) do
  vim.api.nvim_set_hl(0, group, type(spec) == "string" and { link = spec } or spec)
end
